title: PhoenixNetworks Statuspage
baseURL: https://status.phoenixmedia.one
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: Website
      group: Frontend
      description: Webserver and Handler for all Websites.
      link: https://phoenixmedia.one
    - name: Mainframe
      group: Backend
      description: Main Server for alle Applications
      link: https://serv1.phnx.rip
    - name: CDN
      group: Frontend
      description: Content-Delivery-Network
      link: https://cdn.phnx.rip
    - name: Redirector
      description: Custom Redirector for all phnx.rip/* links
      link: https://phnx.rip
    - name: Wordpress
      group: Frontend
      description: Wordpress Installation
      link: https://blog.phoenixmedia.one
    - name: Gameserver
      group: Backend
      link: https://serv1.phnx.rip:81
    - name: Voiceserver
      group: Backend
      link: https://serv1.phnx.rip:81
    - name: Mailserver
      group: Backend
      description: Mailserver for @*.phnx.rip, @phoenixmedia.one and *@mcuproductions.de
    - name: Downloads
      group: Backend
      description: Filetransfer Service
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: " UTC"
  logo: /images/clearstatus.svg
  description_header: Information about <a class='text-grey-darkest' title='Visit
    phoenixmedia.one' href='https://phoenixmedia.one/'>PhoenixNetworks</a>
    systems operations.<br />Follow us <a class='text-grey-darkest' title='Visit
    our page on Twitter' href='https://www.twitter.com/xPhoenixMedia'>on
    Twitter</a> or view our <a class='text-grey-darkest' href='%s'
    >monitoring</a><br />for downtimes and pings.
  copyrightHolder: PhoenixMedia
  eventsPerPage: 10
  iconType: image/png
  groups:
    - Frontend
    - Backend
  icon: /images/clearstatus.png
  description_footer: ""
