title: PhoenixNetworks Statuspage
baseURL: https://status.phoenixmedia.one
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems: []
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: " UTC"
  logo: /images/clearstatus.svg
  description_header: Information about <a class='text-grey-darkest' title='Visit
    phoenixmedia.one' href='https://phoenixmedia.one/'>PhoenixNetworks</a>
    systems operations.<br />Follow us <a class='text-grey-darkest' title='Visit
    our page on Twitter' href='https://www.twitter.com/xPhoenixMedia'>on
    Twitter</a> or subscribe to <a class='text-grey-darkest' href='%s'
    >RSS</a><br />to be alerted of new events.
  copyrightHolder: PhoenixMedia
  eventsPerPage: 10
  iconType: image/png
  groups:
    - Frontend
    - Backend
  icon: /images/clearstatus.png
  description_footer: ""
